# Generated by Django 5.2.5 on 2025-08-10 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_app_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='isProfileComplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='registrationDate',
            field=models.DateField(default=datetime.date(2025, 8, 10)),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.CharField(default='', max_length=100),
        ),
    ]
