# Generated by Django 5.2.5 on 2025-08-12 13:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_registrationdate_apphistory_farmercrops_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation_history', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
