# Generated by Django 5.2.5 on 2025-08-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
    ]
