# Generated by Django 5.2.5 on 2025-08-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_apphistory_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='apphistory',
            name='english_content',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='farmercrops',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmercrops',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
