# Generated by Django 5.2.5 on 2025-08-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_apphistory_english_content_farmercrops_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_phoneNumber', models.CharField(default='', max_length=1000)),
                ('vender_phoneNumber', models.CharField(default='', max_length=1000)),
                ('from_message', models.TextField(default='')),
                ('to_message', models.TextField(default='')),
                ('farmer_name', models.CharField(default='', max_length=1000)),
                ('vender_name', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
