# Generated by Django 5.2.5 on 2025-08-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
