# Generated by Django 5.2.5 on 2025-08-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_messages_user_conversation_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
