# Generated by Django 5.2.5 on 2025-08-12 05:30

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_address_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registrationDate',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='AppHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('content', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_history_records', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerCrops',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('crop_price', models.FloatField(default=0.0)),
                ('quantity', models.FloatField(default=0.0)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_crops', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('crop_price', models.FloatField(default=0.0)),
                ('quantity', models.FloatField(default=0.0)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_crops', to='users.user')),
            ],
        ),
    ]
